In [1]:
import numpy as np
import time

In [2]:
arr=np.array([1,2,4,7])
arr  

array([1, 2, 4, 7])

In [3]:
size=1_000_000

pyList=list(range(size))
start=time.time()
sqList=[x**2 for x in pyList]
end=time.time()
print(f"Python List time {end-start}")

arr=np.array([pyList])
start=time.time()
arr**2
end=time.time()
print(f"Python numpy list time {end-start}")

Python List time 0.17091155052185059
Python numpy list time 0.0067615509033203125


In [4]:
arr=np.array([1,24,5,8,3,9])
print(arr,type(arr),arr.dtype,arr.shape)

arr2=np.array([34,5,73,8,12,"prime"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

[ 1 24  5  8  3  9] <class 'numpy.ndarray'> int64 (6,)
['34' '5' '73' '8' '12' 'prime'] <class 'numpy.ndarray'> <U21 (6,)


In [5]:
arr2D=np.array([[1,2,3,1],
                [4,5,6,1],
                [7,8,9,1]])
print(arr2D,arr2D.shape)

[[1 2 3 1]
 [4 5 6 1]
 [7 8 9 1]] (3, 4)


In [6]:
zeroArr=np.zeros((2,3),dtype="int64")
print(zeroArr,zeroArr.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [7]:
onesArr=np.ones((3,3),dtype="int64")
print(onesArr,onesArr.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]] (3, 3)


In [8]:

arr=np.full((4,6),7)
print(arr)

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


In [9]:
i=np.eye((2))
print(i)

[[1. 0.]
 [0. 1.]]


In [10]:
arr=np.arange(2,20,5)
print(arr)

[ 2  7 12 17]


In [11]:
arr=np.linspace(1,100,4)
print(arr)

[  1.  34.  67. 100.]


In [12]:
# Properties
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)

float=arr.astype(np.float64)
print(float,float.dtype)

(2, 3)
6
2
[[1. 2. 3.]
 [4. 5. 6.]] float64


In [13]:
# Operation on Numpy Array

# Reshaping
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr,arr.shape)
reshape=arr.reshape((3,2))
print(reshape,reshape.shape)

flat=arr.flatten() # 2D to 1D and return Copy
flat[1]=20
print(flat,flat.shape)

ravel=arr.ravel() # 2D to 1D and change Orginal
ravel[1]=20
print(ravel,ravel.shape)
print(arr,arr.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[ 1 20  3  4  5  6] (6,)
[ 1 20  3  4  5  6] (6,)
[[ 1 20  3]
 [ 4  5  6]] (2, 3)


In [14]:
# Indexing On Araay
# arr=np.array([[1,2,3],
#               [4,5,6]])
# print(arr[0][1])
# print(arr[1][1])

# # Fancy Indexing
arr=np.array([1,2,3,4,5,6])
# print(arr[[1,4,5]])

# Boolean Indexing
print(arr[arr>4])


[5 6]


In [15]:
# Slicing 

arr=np.array([1,2,3,4,5,6])
print(arr[1:4])


[2 3 4]


In [16]:
# Copy v View
arr=np.array([1,2,3,4,5])
subArr=arr[1:3].copy()
print(subArr)
subArr[0]=300
print(arr)
print(subArr)


[2 3]
[1 2 3 4 5]
[300   3]


In [3]:
# Data Type
# arr=np.array([1,2,4,6],dtype="int8")
# print(arr,arr.dtype)

arr1=np.array([3+8j])
arr2=np.array([5+2j])
complex=arr1+arr2
print(arr1+arr2,complex.dtype)

[8.+10.j] complex128


In [4]:
# Axes in Multi-Dimensional Array
arr3D=np.array([[[1,2,3],
                 [4,5,6]],
                 [[9,8,7],
                  [6,5,4]]])
print(arr3D,arr3D.shape,arr3D.ndim)

[[[1 2 3]
  [4 5 6]]

 [[9 8 7]
  [6 5 4]]] (2, 2, 3) 3


In [5]:
print(arr3D[0,0,1])

2


In [20]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,arr2d.shape,arr2d.ndim)

summ=np.sum(arr2d)
print(summ)
print()

sum_of_columns=np.sum(arr2d,axis=0)
print(sum_of_columns,sum_of_columns.shape,sum_of_columns.ndim)
print()

sum_of_rows=np.sum(arr2d,axis=1)
print(sum_of_rows,sum_of_rows.shape,sum_of_columns.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 2
45

[12 15 18] (3,) 1

[ 6 15 24] (3,) 1


In [30]:
# 3D Array
# 2 x 2 x 3
arr=np.array([[[1,2,3],
               [4,5,6]],
               [[9,8,7],
                [6,5,9]]])
print(arr.shape)
print(arr[0,1,2])

# Slicing
print(arr[:,0,:])
print(arr[:,:,0:2])

(2, 2, 3)
6
[[1 2 3]
 [9 8 7]]
[[[1 2]
  [4 5]]

 [[9 8]
  [6 5]]]


In [22]:
# Vectorization 
arr=np.array([1,2,3,4,5])
print(arr*2)
print(arr**2)

# Boardcasting
arr=np.array([1,2,3,4,5])
print(arr+5)
arr2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr+arr2)
print(arr.shape," ",arr2.shape)

[ 2  4  6  8 10]
[ 1  4  9 16 25]
[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 7  9 11 13  5]]
(5,)   (2, 5)


In [23]:
# Normalize
arr=np.array([[1,3],[5,7]])
mean=np.mean(arr)
print(f"Mean: {mean}")
std_dev=np.std(arr)
print(f"Std Dev: {std_dev}")
normalize_Arr=(arr-mean)/std_dev
print(normalize_Arr)

Mean: 4.0
Std Dev: 2.23606797749979
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [24]:
# Mathematical Function

# Aggregation

arr=np.array([1,2,3,4,5])
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr.prod())
print(arr.argmax())
print(arr.argmin())
print(arr.var())
print(arr.std())

3.0
5
1
15
120
4
0
2.0
1.4142135623730951


In [25]:
# Power Function
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,6))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[    1    64   729  4096 15625]


In [26]:
# Log 
print(np.log(arr))
print(np.log10(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [27]:
# Rounding
print(np.round(3.49))
print(np.ceil(3.49))
print(np.floor(3.99))
print(np.trunc(3.98))

3.0
4.0
3.0
3.0


In [6]:
arr=np.array([1,-2,4,2,-35,56,3,-4,5])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))
print(np.unique(np.abs(arr)))

[-35  -4  -2   1   2   3   4   5  56]
[-35  -4  -2   1   2   3   4   5  56]
[ 1  2  4  2 35 56  3  4  5]
[ 1  2  3  4  5 35 56]
