# Neuron

In [1]:
import torch
import torch.nn as nn 

In [24]:
# Input
torch.manual_seed(42)
inputs=torch.tensor([1.0,2.0,3.0])

In [25]:
neuron=nn.Linear(in_features=3,out_features=1)

In [26]:
output=neuron(inputs)

In [27]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [28]:
# Verify .. ... Formula
print(neuron.weight)
print(neuron.bias)

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)
Parameter containing:
tensor([0.5304], requires_grad=True)


In [29]:
neuron.weight @ inputs+neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)