In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

# linear Regression

In [ ]:
class linearRegression:
    def __init__(self,learning_Rate=0.01,n_iter=1000):
        self.bias=None
        self.weights=None
        self.lr=learning_Rate
        self.n_iter=n_iter
        
    def fit(self,X,y): #X_train , y_Train
        m,n=X.shape #(number of sample, number of features)

        #Step1 - Initailize params
        self.bias=0
        self.weights=np.zeros(n) #[0,0,0,...,0]

        #Gradient Descent
        for i in range(self.n_iter):
            # Step2 - Calc y_pred
            y_pred =self.bias+np.dot(X,self.weights)

            #Step3 - Calc Gradient
            db= (1/m) + np.sum(y_pred-y)
            dw= (1/m) + np.dot(X.T,(y_pred-y))

            #Step4 - Convergence Theorem - params Update
            self.bias -= self.lr*db
            self.weights -= self.lr*dw
    
    def predict(self,X):
        y_pred=self.bias+ np.dot(X,self.weights)
        return y_pred


In [20]:
X=np.array([[1],[2],[3],[4],[5]])
y=np.array([2,4,6,8,10])


In [21]:
model=linearRegression()
model.fit(X,y)

In [22]:
y_pred=model.predict(X)
y_pred

array([ 1.88010023,  3.92006183,  5.96002343,  7.99998504, 10.03994664])

In [23]:
print(model.bias)
print(model.weights)

-0.15986137904619874
[2.0399616]


# Linear Reg with OLS

In [24]:
# Linear reg with OLS

class LinearRegressionOLS:
    def __init__(self):
        self.bias = None
        self.weights = None

    def fit(self, X, y):
        m, n = X.shape

        X_b = np.c_[np.ones((m, 1)), X]

        # normal equation
        # theta = np.dot( np.linealg.inv(np.dot(X_b.T, X_b)), np.dot(X_b.T, y)) 
        theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y

        self.bias = theta[0]
        self.weights = theta[1:]

    def predict(self, X):
        y_pred = self.bias + np.dot(X, self.weights)
        return y_pred


In [25]:
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2, 4, 6, 8, 10])

model = LinearRegressionOLS()
model.fit(X, y)

y_pred = model.predict(X)
print(y_pred)

print(model.bias)
print(model.weights)

[ 2.  4.  6.  8. 10.]
5.329070518200751e-15
[2.]


# Logistic Regression

In [26]:
# Logistic Regression

class LogisticRegression:
    def __init__(self, learning_rate=0.1, n_iter=1000):
        self.bias = None
        self.weights = None
        self.lr = learning_rate
        self.n_iter = n_iter

    def _sigmoid(self, z):
        return (1 / (1 + np.exp(-z)))

    def fit(self, X, y):
        m, n = X.shape

        self.bias = 0
        self.weights = np.zeros(n)

        for i in range(self.n_iter):
            z = self.bias + np.dot(X, self.weights)
            y_pred = self._sigmoid(z)

            db = (1/m) * (y_pred - y)
            dw = (1/m) * np.dot(X.T, (y_pred - y))
            
            self.bias -= self.lr * db
            self.weights -= self.lr * dw
    
    def get_probabilities(self, X):
        z = self.bias + np.dot(X, self.weights)
        return self._sigmoid(z)
        
    def predict(self, X, threshold=0.5):
        probabilities = self.get_probabilities(X)
        y_pred_bool = probabilities >= threshold
        return y_pred_bool.astype(int)

In [27]:
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]])
y = np.array([0, 0, 1, 1])

model = LogisticRegression()
model.fit(X, y)

y_pred = model.predict(X)
print(y_pred)

print(model.get_probabilities(X))

[0 0 1 1]
[0.03701722 0.04694058 0.972997   0.98153106]
