In [91]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score,accuracy_score,precision_score,confusion_matrix,classification_report

In [92]:
df = sns.load_dataset("iris")
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [94]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [95]:
df.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [96]:
df["species"].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [97]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [98]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

# Logistic Regression

In [99]:
X=df.drop(columns="species")
y=df["species"]

In [100]:
y=y.map({
    "setosa":1,
    "versicolor":2,
    "virginica":3

})

In [101]:
y


0      1
1      1
2      1
3      1
4      1
      ..
145    3
146    3
147    3
148    3
149    3
Name: species, Length: 150, dtype: int64

In [102]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

In [103]:
model=LogisticRegression(max_iter=1500)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1500)

In [104]:
y_pred=model.predict(X_test)
y_pred

array([2, 1, 3, 2, 2, 1, 2, 3, 2, 2, 3, 1, 1, 1, 1, 2, 3, 2, 2, 3, 1, 3,
       1, 3, 3, 3, 3, 3, 1, 1])

In [105]:
X_test.count()

sepal_length    30
sepal_width     30
petal_length    30
petal_width     30
dtype: int64

In [106]:
y_test.count()

np.int64(30)

In [107]:
print("Recall:", recall_score(y_test, y_pred, average="weighted"))
print("Precision:", precision_score(y_test, y_pred, average="weighted"))
print("Accuracy:", accuracy_score(y_test, y_pred))


Recall: 1.0
Precision: 1.0
Accuracy: 1.0


# Naive Bayes


In [108]:
gnb_model=GaussianNB()
gnb_model.fit(X_train,y_train)

GaussianNB()

In [109]:
y_pred=gnb_model.predict(X_test)
y_pred

array([2, 1, 3, 2, 2, 1, 2, 3, 2, 2, 3, 1, 1, 1, 1, 2, 3, 2, 2, 3, 1, 3,
       1, 3, 3, 3, 3, 3, 1, 1])

In [110]:
from sklearn.metrics import recall_score,accuracy_score,precision_score,confusion_matrix,classification_report,r2_score


print("Recall:", recall_score(y_test, y_pred, average="weighted"))
print("Precision:", precision_score(y_test, y_pred, average="weighted"))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("confusion_matrix: ",confusion_matrix(y_test,y_pred))
print("\n")
print("classification_report:\n",classification_report(y_test,y_pred))

Recall: 1.0
Precision: 1.0
Accuracy: 1.0
confusion_matrix:  [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


classification_report:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         9
           3       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# KNN

In [116]:
scalar=StandardScaler()
X_train_scaled=scalar.fit_transform(X_train)
X_test_scaled=scalar.transform(X_test)


In [120]:
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scaled,y_train)
y_pred=knn.predict(X_test_scaled)
print("precision_score",precision_score(y_test,y_pred,average="weighted"))
print("recall_score",recall_score(y_test,y_pred,average="weighted"))
print("accuracy_score",accuracy_score(y_test,y_pred))

precision_score 1.0
recall_score 1.0
accuracy_score 1.0


In [121]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled,y_train)
y_pred=knn.predict(X_test_scaled)
print("precision_score",precision_score(y_test,y_pred,average="weighted"))
print("recall_score",recall_score(y_test,y_pred,average="weighted"))
print("accuracy_score",accuracy_score(y_test,y_pred))

precision_score 1.0
recall_score 1.0
accuracy_score 1.0


In [122]:
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train_scaled,y_train)
y_pred=knn.predict(X_test_scaled)
print("precision_score",precision_score(y_test,y_pred,average="weighted"))
print("recall_score",recall_score(y_test,y_pred,average="weighted"))
print("accuracy_score",accuracy_score(y_test,y_pred))

precision_score 1.0
recall_score 1.0
accuracy_score 1.0


In [124]:
from sklearn.model_selection import GridSearchCV

classifer=KNeighborsClassifier()
param_grid={"n_neighbors":[3,5,7,9]}
classifierCV=GridSearchCV(classifer,param_grid,cv=5,scoring="recall")
classifierCV.fit(X_train_scaled,y_train)

d:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "d:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "d:\Anaconda\Lib\site-packages\sklearn\metrics\_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda\Lib\site-packages\sklearn\metrics\_scorer.py", line 388, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 216, in wrapper
    return func(*a

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [3, 5, 7, 9]}, scoring='recall')

In [125]:
y_pred=classifierCV.predict(X_test_scaled)
y_pred

array([2, 1, 3, 2, 2, 1, 2, 3, 2, 2, 3, 1, 1, 1, 1, 2, 3, 2, 2, 3, 1, 3,
       1, 3, 3, 3, 3, 3, 1, 1])

In [128]:
print("accuracy_score",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average="weighted"))
print("recall_score",recall_score(y_test,y_pred,average="weighted"))

accuracy_score 1.0
precision_score 1.0
recall_score 1.0


In [130]:
#Result
res=pd.DataFrame(classifierCV.cv_results_)
res
res[["param_n_neighbors","mean_test_score"]]

,param_n_neighbors,mean_test_score
0,3,NaN
1,5,NaN
2,7,NaN
3,9,NaN


In [131]:
print(classifierCV.best_params_)

{'n_neighbors': 3}


In [135]:
from sklearn.pipeline import Pipeline

pipe = Pipeline([('scaler', StandardScaler()), ('knn', KNeighborsClassifier())])

param_grid={"knn__n_neighbors":[3,5,7,9]}
classifierCV=GridSearchCV(pipe,param_grid,cv=5,scoring="recall_weighted")
classifierCV.fit(X_train,y_train)
y_pred=classifierCV.predict(X_test)

print("accuracy_score",accuracy_score(y_test,y_pred))
print("precision_score",precision_score(y_test,y_pred,average="weighted"))
print("recall_score",recall_score(y_test,y_pred,average="weighted"))

print(classifierCV.best_params_)

accuracy_score 1.0
precision_score 1.0
recall_score 1.0
{'knn__n_neighbors': 3}
